# Generated by Django 3.2.5 on 2021-07-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20210726_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
