# Generated by Django 3.2.5 on 2021-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%y-%m-%d/'),
            preserve_default=False,
        ),
    ]
