# Generated by Django 3.2.5 on 2021-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chapter',
            field=models.FileField(blank=True, null=True, upload_to='chapter/%Y-%m-%D/'),
        ),
    ]
