# Generated by Django 3.2.5 on 2021-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_game_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='chapter',
        ),
    ]
