# Generated by Django 3.2.5 on 2021-07-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_remove_game_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(upload_to='file/%y-%m-%d/'),
        ),
    ]
